// src/agenda/tratamientos.js

export const TRATAMIENTOS = [
    {
      id: 'FON-INF-EVAL-ONLINE',
      especialidad: 'Fonoaudiología Infanto-Juvenil',
      categoria: 'Fonoaudiología Infanto-Juvenil',
      tratamiento: 'Evaluación fonoaudiológica infanto-juvenil online',
      codigoFonasa: '13-02-2003',
      descripcion: 'Evaluación de voz, habla y lenguaje',
      valor: 35000,
      profesionalesIds: [1, 2],
    },
    {
      id: 'FON-ADULTO-EVAL-ONLINE',
      especialidad: 'Fonoaudiología Adulto',
      categoria: 'Fonoaudiología Adulto',
      tratamiento: 'Evaluación fonoaudiológica adulto online',
      codigoFonasa: '13-02-2003',
      descripcion: 'Evaluación de voz, habla y lenguaje',
      valor: 35000,
      profesionalesIds: [1],
    },
    {
      id: 'PSI-ADULTO-ONLINE',
      especialidad: 'Psicología Adulto',
      categoria: 'Psicología Adulto',
      tratamiento: 'Evaluación Psicología Adulto online',
      codigoFonasa: '09-02-2001',
      descripcion: 'Psicodiagnóstico',
      valor: 30000,
      profesionalesIds: [3, 4],
    },
    {
      id: 'PSI-INFANTO-ONLINE',
      especialidad: 'Psicología Infanto-Juvenil',
      categoria: 'Psicología Infanto-Juvenil',
      tratamiento: 'Evaluación Psicología Infanto-Juvenil online',
      codigoFonasa: '09-02-2001',
      descripcion: 'Psicodiagnóstico',
      valor: 30000,
      profesionalesIds: [3, 4, 5],
    },
    {
      id: 'PACK-PSI-BIENESTAR',
      especialidad: 'Pack Psicologia',
      categoria: 'Pack Psicologia',
      tratamiento: 'Pack Bienestar Emocional (4 sesiones Psicologia online)',
      codigoFonasa: 'PACK-PSI',
      descripcion: 'Tratamiento Psicología Mensual (4 sesiones)',
      valor: 90000,
      profesionalesIds: [3, 4, 5],
    },
    {
      id: 'MAT-ADULTO-ONLINE',
      especialidad: 'Matrona Adulto Teleconsulta',
      categoria: 'Matrona',
      tratamiento: 'Consulta Matrona adulto online',
      codigoFonasa: '11-01-1942',
      descripcion: 'Consulta matrona',
      valor: 18000,
      profesionalesIds: [6],
    },
  ];
  